steps:
# Build the image that encapsulates the pipeline.
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_TFX_IMAGE_NAME:$TAG_NAME', '.']
  dir: $_PIPELINE_FOLDER

- name: 'gcr.io/$PROJECT_ID/tfx-cli'
  args: ['pipeline', 'create', '--engine', 'kubeflow', '--pipeline_path', '$_PIPELINE_DSL', '--endpoint', '$_ENDPOINT']
  env: 
  - 'GCP_REGION=$_GCP_REGION'  
  - 'PROJECT_ID=$PROJECT_ID'
  - 'PIPELINE_NAME=${_PIPELINE_NAME}-${TAG_NAME}'
  - 'MODEL_NAME=$_MODEL_NAME'  
  - 'ARTIFACT_STORE_URI=$_ARTIFACT_STORE_URI'
  - 'CUSTOM_SERVICE_ACCOUNT=$_CUSTOM_SERVICE_ACCOUNT'
  - 'DATA_ROOT_URI=$_DATA_ROOT_URI'
  - 'KUBEFLOW_TFX_IMAGE=gcr.io/$PROJECT_ID/$_TFX_IMAGE_NAME:$TAG_NAME'
  - 'RUNTIME_VERSION=_$_RUNTIME_VERSION'
  - 'PYTHON_VERSION=$_PYTHON_VERSION'
  - 'USE_KFP_SA=$_USE_KFP_SA'
  - 'ENABLE_TUNING=$_ENABLE_TUNING'
  dir: $_PIPELINE_FOLDER

# Push the custom image to Container Registry 
images: ['gcr.io/$PROJECT_ID/$_TFX_IMAGE_NAME:$TAG_NAME']

options:
  logging: CLOUD_LOGGING_ONLY
